implement tagcolor features
AY1920S1-CS2103T-W11-1/main pull request #214
Opened 2019-11-04 14:20 UTC by LuWenQ

closes #120

2019-11-05 09:51 UTC, jiayushe requested changes
Hmm can't you just use the `edittag` command to change the colors? The user should be allowed to specify the tag color upon creating new tags as well.

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +            + "[" + PREFIX_TAG_COLOR + "TAGCOLOR] \n"
This field shouldn't be optional.

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +    public static final String MESSAGE_DUPLICATE_TAG = "This Tag already exists in the algobase.";
Why do we need this?

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +    public static final String MESSAGE_EDIT_TAG_SUCCESS = "Edited Tag: %1$s";
Follow the same format for the other command messages.

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +        requireNonNull(color);
Use `requireAllNonNull`.

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +        }
Hmm you are simply changing the colors, how can duplicates be possible? Duplicates are based on tag names only right?

2019-11-05 09:51 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/commands/EditTagColorCommand.java
> +        assert color != null;
Use `requireAllNonNull`.

2019-11-06 16:33 UTC, jiayushe requested changes
Can you address my previous review as well? Thanks.

2019-11-06 16:33 UTC, jiayushe commented on src/test/java/seedu/algobase/logic/commands/HelpCommandTest.java
> +    private static final String EXPECTED_COMMAND_LIST = "Available commands are: [add, addplan, addtag, "
This is outdated.

2019-11-06 16:33 UTC, jiayushe commented on src/main/java/seedu/algobase/model/tag/Tag.java
> +    }
What is the purpose of this method? Always return `true`?

2019-11-06 16:33 UTC, jiayushe commented on src/main/java/seedu/algobase/model/tag/Tag.java
> +        checkArgument(isValidTagName(tagName), MESSAGE_CONSTRAINTS);
These 2 lines should be updated accordingly.

2019-11-07 18:11 UTC, LuWenQ commented
Got bug in storage

2019-11-09 03:05 UTC, le0tan requested changes
Have you updated the UG for `addtag` and the `MESSAGE_USAGE` in `AddTagCommand`?
And can you check if your changes affect other parts of DG & UG?

2019-11-09 03:05 UTC, le0tan commented on docs/UserGuide.adoc
> +Tag color can only be "RED" "ORANGE" "YELLOW" "GREEN" "BLUE" "PURPLE" "TEAL" "BLACK" and "DEFAULT".
**or** "DEFAULT"

2019-11-09 12:25 UTC, le0tan approved these changes

2019-11-09 12:34 UTC, jiayushe approved these changes
LGTM

2019-11-09 12:37 UTC, merged