Plan(cannot add or edit tasks in plans)
AY1920S1-CS2103T-W11-1/main pull request #65
Opened 2019-10-12 21:16 UTC by Seris370

I guess this PR cannot be automatically merged because I opened this branch when some latest PRs hadn't been merged...?

2019-10-13 06:15 UTC, jiayushe commented
> Some conflicts are due to refactored MESSAGEs. Command 'lsplan' is changed to 'listplan'.
> Didn't touch Ui part.

Can you try to rebase your commits and resolve the conflicts manually?

This command should suffice: `git pull --rebase https://github.com/AY1920S1-CS2103T-W11-1/main.git master`.

2019-10-13 06:23 UTC, jiayushe requested changes
Please rebase your commits to current master. Also try to add some simple/placeholder tests if possible.

2019-10-13 06:23 UTC, jiayushe commented on README.adoc
> +Technical interviews are hard. Unless you are extraordinarily gifted, you will likely have to do tonnes of practice questions to ace them. And there are so many practice websites to choose from - Lee
Why are you changing `name` to `planName` in this line?

2019-10-13 06:23 UTC, jiayushe commented on config/checkstyle/checkstyle.xml
> +        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
I don't think the changes in this file are relavant here, can you revert them?

2019-10-14 00:46 UTC, le0tan approved these changes
Closes #39

2019-10-14 00:46 UTC, le0tan commented on src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
> +            + PREFIX_END_DATE + "END_DATE "
Need a new line here.

2019-10-14 00:46 UTC, le0tan commented on src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
> +            + "[" + PREFIX_END_DATE + "END_DATE] "
New line here.

2019-10-14 00:46 UTC, le0tan commented on src/main/java/seedu/algobase/logic/commands/FindPlanCommand.java
> +public class FindPlanCommand extends Command {
I'll implement `findplan` that's similar to `find` later, which supports searching by more fields.

2019-10-14 00:46 UTC, le0tan commented on src/main/java/seedu/algobase/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_PLAN_NAME = new Prefix("n/");
These are existing prefixes so no need to re-declare them.

2019-10-14 00:46 UTC, le0tan commented on src/main/java/seedu/algobase/logic/parser/ParserUtil.java
> +     * @throws ParseException if the given {@code name} is invalid.
I suppose it's not required to write thrown exception in JavaDoc for this project? (checkstyle doesn't complain on this anyways...)

2019-10-14 02:08 UTC, jiayushe commented on config/checkstyle/checkstyle.xml
> +        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
Can you revert the changes in this file?

2019-10-14 02:20 UTC, jiayushe requested changes

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/AlgoBase.java
> +
This method should be under plan-level operations.

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/Model.java
> -    ObservableList<Plan> getFilteredPlanList();
Move the plan-level methods here.

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/ModelManager.java
> +    public void updateFilteredPlanList(Predicate<Plan> predicate) {
Why is this under `Util`?

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/plan/Plan.java
> +
Why new line here?

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/plan/Plan.java
> +                .append(" PlanDescription: ")
Hmm this is for displaying purpose, so either `Description` or `Plan Description`?

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/plan/UniquePlanList.java
> +public class UniquePlanList implements Iterable<Plan> {
I don't think we need to enforce uniqueness on plans? @le0tan What do you think?

There is already an existing PlanList class anyway, so remove this class and modify the other one if necessary.

2019-10-14 02:20 UTC, jiayushe commented on src/main/java/seedu/algobase/model/plan/exceptions/DuplicatePlanException.java
> +public class DuplicatePlanException extends RuntimeException {
Same as above. I don't think we need uniqueness on plans.

2019-10-14 02:20 UTC, jiayushe commented on src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
> +
Add `throw new AssertionError("This method should not be called.");` in the method body to be consistent with the rest.

2019-10-14 11:39 UTC, jiayushe requested changes

2019-10-14 11:39 UTC, jiayushe commented on src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
> +        return false;
Hmm should be `throw new AssertionError("This method should not be called.");` right?

2019-10-14 12:22 UTC, jiayushe approved these changes

2019-10-14 12:22 UTC, jiayushe commented on src/main/java/seedu/algobase/logic/parser/AddPlanCommandParser.java
> +            startDate = LocalDateTime.now();
Fix this in next PR.

2019-10-14 12:24 UTC, merged